
import { GoogleGenAI, Type } from "@google/genai";
import { VerificationResult, DetectionType } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const analyzeContent = async (
  type: DetectionType,
  content: string | { data: string; mimeType: string },
  modelName: string = "gemini-3-flash-preview",
  additionalContext?: string
): Promise<VerificationResult> => {
  const model = modelName;
  
  let prompt = "";
  let contents: any = null;

  switch (type) {
    case DetectionType.TEXT:
      prompt = `Act as a world-class fact-checker. Analyze: "${content}". Determine if TRUE or FAKE. Provide integer confidence 0-100.`;
      contents = prompt;
      break;
    
    case DetectionType.IMAGE:
      prompt = `Act as a visual forensic expert. Analyze this image. Determine if TRUE (authentic) or FAKE (manipulated/AI). Provide integer confidence 0-100.`;
      if (typeof content !== 'string') {
        contents = {
          parts: [
            { text: prompt },
            { inlineData: { data: content.data, mimeType: content.mimeType } }
          ]
        };
      }
      break;

    case DetectionType.ACADEMIC:
      prompt = `Act as a Professor evaluating a student paper. Detect if this text is AI_GENERATED or HUMAN_WRITTEN: "${content}". 
      Analyze for "Perplexity" (complexity) and "Burstiness" (variation in sentence structure). 
      Provide an integer confidence score 0-100.`;
      contents = prompt;
      break;

    case DetectionType.CODE:
      prompt = `Act as a senior software architect. Detect if this source code was generated by an AI (Copilot/ChatGPT) or a human developer: "${content}". 
      Look for boilerplate patterns, lack of comments, or overly perfect formatting. 
      Return AI_GENERATED or HUMAN_WRITTEN with integer confidence 0-100.`;
      contents = prompt;
      break;

    case DetectionType.EMAILS:
      prompt = `Act as a cybersecurity analyst. Detect if this email is an AI-generated phishing/spam attempt or a genuine human communication: "${content}". 
      Return AI_GENERATED or HUMAN_WRITTEN with integer confidence 0-100.`;
      contents = prompt;
      break;

    case DetectionType.CREATIVE:
      prompt = `Act as a literary critic. Detect if this creative writing/story is AI-generated: "${content}". 
      Return AI_GENERATED or HUMAN_WRITTEN with integer confidence 0-100.`;
      contents = prompt;
      break;

    default:
      prompt = "Analyze the provided information.";
      contents = prompt;
  }

  try {
    const response = await ai.models.generateContent({
      model,
      contents,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            status: { 
              type: Type.STRING, 
              enum: ['TRUE', 'FAKE', 'AI_GENERATED', 'HUMAN_WRITTEN', 'UNCERTAIN'] 
            },
            confidence: { type: Type.INTEGER },
            analysis: { type: Type.STRING },
            metrics: {
              type: Type.OBJECT,
              properties: {
                perplexity: { type: Type.STRING },
                burstiness: { type: Type.STRING },
                readability: { type: Type.STRING }
              }
            },
            sources: { type: Type.ARRAY, items: { type: Type.STRING } }
          },
          required: ["status", "confidence", "analysis"]
        }
      }
    });

    const text = response.text || "{}";
    const parsed = JSON.parse(text);
    if (parsed.confidence > 0 && parsed.confidence <= 1) parsed.confidence *= 100;
    return parsed;
  } catch (error) {
    console.error("Gemini Error:", error);
    return { status: 'UNCERTAIN', confidence: 0, analysis: "Verification failed." };
  }
};
